In [2]:
import numpy as np
import sympy as sym
import matplotlib.pyplot as plt

In [3]:
A = np.random.randn(3,3)

# its inverse
Ai = np.linalg.inv(A)

# should be identity
A@Ai

array([[ 1.00000000e+00,  7.46491641e-17,  1.25112603e-16],
       [-3.09147862e-16,  1.00000000e+00,  3.35156421e-16],
       [ 2.18332243e-19,  4.06125613e-17,  1.00000000e+00]])

In [4]:
# matrix
A  = np.random.randn(3,3)

# concatenated by identity
Acat = np.concatenate((A,np.eye(3,3)),axis=1)

# RREF (via sympy)
Ar = sym.Matrix(Acat).rref()[0] # RREF

# keep inverse
Ar = Ar[:,3:]

# numpy's inv
Ai = np.linalg.inv(A)

# compare
Ar-Ai

Matrix([
[-5.55111512312578e-17,                     0,  2.22044604925031e-16],
[                    0,  2.22044604925031e-16,  2.22044604925031e-16],
[                    0, -2.22044604925031e-16, -2.22044604925031e-16]])

In [5]:
# tall matrix
A = np.random.randn(5,3)

# left inverse
Al = np.linalg.inv(A.T@A)@A.T

# check for I
Al@A

array([[ 1.00000000e+00, -7.39606337e-17, -1.85811350e-17],
       [-7.83889955e-17,  1.00000000e+00,  6.71961929e-18],
       [-1.55457911e-16, -2.71387435e-17,  1.00000000e+00]])

In [6]:
# reduced-rank matrix
A = np.random.randn(3,3)
A[1,:] = A[0,:]

# pseudoinverse
Api = np.linalg.pinv(A)

# identity matrix?
Api@A

array([[ 0.65287739, -0.09998992, -0.46543584],
       [-0.09998992,  0.97119755, -0.13407047],
       [-0.46543584, -0.13407047,  0.37592507]])

In [7]:
# create matrix
m = 4
A = np.random.randn(m,m)

# initialize
M = np.zeros((m,m))
G = np.zeros((m,m))

# compute minors matrix
for i in range(m):
    for j in range(m):

        # select rows and cols
        rows = [True]*m
        rows[i] = False

        cols = [True]*m
        cols[j] = False

        M[i,j]=np.linalg.det(A[rows,:][:,cols])

        # compute G
        G[i,j] = (-1)**(i+j)


# compute C
C = M * G

# compute A
Ainv = C.T / np.linalg.det(A)

# 'regular' inverse function
AinvI = np.linalg.inv(A)

# compare against inv()
AinvI-Ainv

array([[-2.22044605e-16,  2.22044605e-16,  2.22044605e-16,
         0.00000000e+00],
       [ 8.32667268e-17,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  1.11022302e-16,  5.55111512e-17,
         0.00000000e+00],
       [-5.55111512e-17,  1.11022302e-16,  0.00000000e+00,
         0.00000000e+00]])

In [8]:
# square matrix
A   = np.random.randn(5,5)
Ai  = np.linalg.inv(A)
Api = np.linalg.pinv(A)
# test equivalence
print(Ai - Api)



# tall matrix
T   = np.random.randn(5,3)
Tl  = np.linalg.inv(T.T@T)@T.T # left inv
Tpi = np.linalg.pinv(T) # pinv
# test equivalence
print(Tl - Tpi)

[[-6.66133815e-16 -1.11022302e-15  5.55111512e-17 -4.44089210e-16
   5.55111512e-16]
 [-2.22044605e-16 -2.22044605e-16  5.55111512e-17  1.11022302e-16
   5.55111512e-17]
 [ 5.55111512e-16  6.66133815e-16  2.77555756e-17 -1.11022302e-15
  -5.55111512e-16]
 [-3.81639165e-16 -4.44089210e-16  2.77555756e-17  0.00000000e+00
   3.88578059e-16]
 [ 3.33066907e-16  5.27355937e-16  1.38777878e-17 -3.33066907e-16
  -1.66533454e-16]]
[[-1.11022302e-16 -6.93889390e-17  1.11022302e-16 -9.71445147e-17
   7.28583860e-17]
 [-1.11022302e-16 -5.55111512e-17  5.55111512e-17 -2.22044605e-16
   1.66533454e-16]
 [-1.66533454e-16 -2.77555756e-17 -1.11022302e-16  1.11022302e-16
  -5.55111512e-17]]
