In [1]:
import numpy as np

In [10]:
# two matrices
M1 = np.random.randn(4,3)
M2 = np.random.randn(3,5)

# and their product
C = M1 @ M2

In [11]:
A = np.random.randn(2,2)
B = np.random.randn(2,2)

# notice that C1 != C2
C1 = A@B
C2 = B@A

In [12]:
M1 = np.random.randn(4,3)
M2 = np.random.randn(4,3)
C = M1 * M2

In [13]:
A = np.array([ [1,2,3],[4,5,6] ])
A.flatten(order='F')

array([1, 4, 2, 5, 3, 6])

In [14]:
A = np.random.randn(4,3)
B = np.random.randn(4,3)

# the transpose-trace trick for the frobenius dot product
f = np.trace(A.T@B)

In [15]:
A = np.random.randn(4,3)
np.linalg.norm(A,'fro')

2.8701776941996684

In [16]:
# two matrices
A = np.random.randn(2,4)
B = np.random.randn(4,3)

# initialize product
C1 = np.zeros((2,3))

# sum over columns
for i in range(4):
    C1 += np.outer(A[:,i],B[i,:])

# show equality
C1 - A@B

array([[-1.11022302e-16,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.11022302e-16]])

In [17]:
# a diagonal matrix and a full one
D = np.diag(np.arange(1,5))
A = np.random.randn(4,4)

# two kinds of products
C1 = D*A
C2 = D@A

# are they the same?
print(np.diag(C1))
print(np.diag(C2))

[-1.80233274 -1.51450995  0.94507251 -0.6303924 ]
[-1.80233274 -1.51450995  0.94507251 -0.6303924 ]


In [18]:
# diagonal matrix
A = np.diag(np.random.rand(3))

# two symmetric matrices
C1 = (A.T+A)/2
C2 = A.T@A

# are they the same?
C1-np.sqrt(C2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# a matrix and a vector (walk into a bar...)
m = 5
A = np.random.randn(m,m)
v = np.random.randn(m)

# the two sides of the equation
LHS = np.linalg.norm(A@v)
RHS = np.linalg.norm(A,ord='fro') * np.linalg.norm(v)

# should always be positive
RHS-LHS

6.581707349830767