In [4]:
import numpy as np

In [5]:
# create data
n = 200
X = np.random.randn(n,4)

# mean-center
X = X-np.mean(X,axis=0)

# covariance
covM = X.T@X / (n-1)

# standard deviations matrix
stdM = np.linalg.inv( np.diag(np.std(X,axis=0,ddof=1)) )

# "manual" correlation matrix
corM = stdM@ X.T@X @stdM / (n-1)

# compare ours against numpy's
print(np.round(covM-np.cov(X.T),3)), print(' ')
print(np.round(corM-np.corrcoef(X.T),3))

[[ 0. -0.  0.  0.]
 [-0.  0. -0.  0.]
 [ 0. -0.  0.  0.]
 [ 0.  0.  0.  0.]]
 
[[ 0. -0.  0. -0.]
 [-0.  0. -0.  0.]
 [ 0. -0. -0.  0.]
 [ 0.  0. -0. -0.]]
